product:
  service:
    url: http://localhost:8081

dubbo:
  application:
    name: cart-service-pro
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
spring:
  profile:
    active: pro
  datasource:
    url: jdbc:mysql://localhost:3306/byte_sale_cart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.sale.model