product:
  service:
    url: http://localhost:8081

dubbo:
  application:
    name: cart-service-test
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false

spring:
  profile:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/byte_sale_cart?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.sale.model