spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-pay-${spring.profiles.active}.yaml

# 分布式id生成器配置
uid-generator:
  #workerId获取方式：none：随机数获取；db：数据库；redis：redis（集群或单机）；zk：（zk集群或单机）
  assigner-mode: db
  time-bits: 29
  worker-bits: 21
  seq-bits: 13
  epoch-str: 2025-1-1
  #boost-power: 3 #可选配置, 如未指定将采用默认值
  #padding-factor: 50 #可选配置, 如未指定将采用默认值
  #schedule-interval:  #可选配置, 如未指定则不启用此功能
  datasource: #使用独立的数据源,如未指定将采用应用系统的数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uid-db
    password: root
    username: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.sale.model

alipay:
  appId: 2021005116689864
  sellerId:
  gatewayUrl: https://openapi.alipay.com/gateway.do
  merchantPrivateKey:
  alipayPublicKey:
  contentKey: