spring:
  datasource:
    url: jdbc:mysql://localhost:3306/byte_sale_payment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.sale.model